<a href="https://colab.research.google.com/github/devthumos/Processamento_de_Linguagem_Natural/blob/main/Atividade_avaliativa_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Competição KAGGLE

## DICIONÁRIO 1

In [396]:
import pandas as pd
import re

path = "https://raw.githubusercontent.com/viniciusrpb/cic0269_natural_language_processing/main/resources/LIWC2007_Portugues_win.dic"

dataset = pd.read_csv(path, sep="\t", encoding="cp860", nrows=21)
# with open("https://raw.githubusercontent.com/viniciusrpb/cic0269_natural_language_processing/main/resources/LIWC2007_Portugues_win.dic", "r") as file:
  # teste = file.read()

In [397]:
dataset

          %
1     funct
2   pronoun
3     ppron
4         i
5        we
6       you
7     shehe
8      they
9     ipron
10  article
11     verb
12  auxverb
13     past
14  present
15   future
16   adverb
17    preps
18     conj
19   negate
20    quant
21   number

In [398]:
dataset = dataset.drop(index=[20, 19, 15, 14, 13, 8, 7, 6, 5, 4, 1, 9])
dataset["%"][16] = "ADV"
dataset["%"][2] = "PRON"
dataset["%"][17] = "ADP"
dataset["%"][12] = "AUX"
dataset["%"][3] = "PROPN"
dataset["%"][18] = "CONJ"
dataset["%"][11] = "VERB"
dataset["%"][21] = "NUM"
dataset["%"][10] = "ART"

dataset

        %
2    PRON
3   PROPN
10    ART
11   VERB
12    AUX
16    ADV
17    ADP
18   CONJ
21    NUM

In [399]:
indexes = dataset.index.tolist()
indexes

[2, 3, 10, 11, 12, 16, 17, 18, 21]

In [400]:
tags = dataset["%"].tolist()

dict_tags = {str(index): tags for index, tags in zip(indexes, tags)}
dict_tags

{'10': 'ART',
 '11': 'VERB',
 '12': 'AUX',
 '16': 'ADV',
 '17': 'ADP',
 '18': 'CONJ',
 '2': 'PRON',
 '21': 'NUM',
 '3': 'PROPN'}

In [401]:
count = 0
dict_tags1 = {}
line = ""
list_word = []
with open("/content/LIWC2007_Portugues_win.dic.txt", "r", encoding="cp1252") as file:
  for line in file:
    text = line.split()
    # print(text)
    for tag in dict_tags:
      # print(tag)
      if tag in text:
        dict_tags1[text[0]] = dict_tags[tag]
        # print(dict_tags1[text[0]])
    count += 1
    # if count == 80:
    #   break

## DICIONÁRIO 2

In [402]:
path = "https://raw.githubusercontent.com/viniciusrpb/cic0269_natural_language_processing/main/resources/SentiLex-lem-PT02.txt"
sentlix_dataset = pd.read_csv(path, sep=".", encoding="utf-8")
sentlix_dataset.head()

   à-vontade      PoS=N;TG=HUM:N0;POL:N0=1;ANOT=MAN
0    abafado  PoS=Adj;TG=HUM:N0;POL:N0=-1;ANOT=JALC
1   abafante   PoS=Adj;TG=HUM:N0;POL:N0=-1;ANOT=MAN
2   abaixado  PoS=Adj;TG=HUM:N0;POL:N0=-1;ANOT=JALC
3    abalado  PoS=Adj;TG=HUM:N0;POL:N0=-1;ANOT=JALC
4  abalizado   PoS=Adj;TG=HUM:N0;POL:N0=1;ANOT=JALC

In [403]:
dict_tags2 = {}
count = 0
def split_sentilex(sentence):
  global count, dict_tags2
  classe = re.split(r"[=|;]", sentence)
  classe = classe[1]
  if classe not in ["IDIOM", "V"]:
    if classe == "Adj":
      classe = "ADJ"
    else:
      classe = "NOUN"
    dict_tags2[sentlix_dataset.iloc[count][0]] = classe

  count += 1
  return sentence

In [404]:
sentlix_dataset["PoS=N;TG=HUM:N0;POL:N0=1;ANOT=MAN"].apply(split_sentilex)

0       PoS=Adj;TG=HUM:N0;POL:N0=-1;ANOT=JALC
1        PoS=Adj;TG=HUM:N0;POL:N0=-1;ANOT=MAN
2       PoS=Adj;TG=HUM:N0;POL:N0=-1;ANOT=JALC
3       PoS=Adj;TG=HUM:N0;POL:N0=-1;ANOT=JALC
4        PoS=Adj;TG=HUM:N0;POL:N0=1;ANOT=JALC
                        ...
7008     PoS=Adj;TG=HUM:N0;POL:N0=-1;ANOT=MAN
7009       PoS=N;TG=HUM:N0;POL:N0=-1;ANOT=MAN
7010    PoS=Adj;TG=HUM:N0;POL:N0=-1;ANOT=JALC
7011     PoS=Adj;TG=HUM:N0;POL:N0=-1;ANOT=MAN
7012     PoS=Adj;TG=HUM:N0;POL:N0=-1;ANOT=MAN
Name: PoS=N;TG=HUM:N0;POL:N0=1;ANOT=MAN, Length: 7013, dtype: object

## DICIONÁRIO 3

In [405]:
dict_tags3 = {
    ".": "PUNCT",
    "?": "PUNCT",
    "!": "PUNCT",
    ":": "PUNCT",
    ",": "PUNCT",
    "...": "PUNCT",
    "-": "PUNCT",
    ";": "PUNCT",
    "'": "PUNCT",
    "\"": "PUNCT",
    "(": "PUNCT",
    ")": "PUNCT",
    "@": "SYM",
    "#": "SYM",
    "$": "SYM",
    "%": "SYM",
    "¨": "SYM",
    "&": "SYM",
    "*": "SYM",
    "+": "SYM",
    "+": "SYM",
    "§": "SYM",
    "[": "SYM",
    "]": "SYM",
    "{": "SYM",
    "}": "SYM",
    "ª": "SYM",
    "º": "SYM",
    "°": "SYM",
}

## TESTANDO NOSSOS DICIONÁRIOS

In [406]:
test_values1 = set()

for key in dict_tags1:
  test_values1.add(dict_tags1[key])

In [407]:
test_values2 = set()

for key in dict_tags2:
  test_values2.add(dict_tags2[key])

In [408]:
test_values3 = set()

for key in dict_tags3:
  test_values3.add(dict_tags3[key])

In [409]:
print(test_values1, test_values2, test_values3, sep="\n")

{'VERB', 'ADP', 'NUM', 'ART', 'PRON', 'AUX', 'ADV', 'CONJ', 'PROPN'}
{'ADJ', 'NOUN'}
{'PUNCT', 'SYM'}

## MERGE DICIONÁRIOS

In [410]:
final_dict_tags = dict_tags1; final_dict_tags.update(dict_tags2); final_dict_tags.update(dict_tags3)

## TESTANDO NOSSO DICIONÁRIO FINAL

In [411]:
test_values = set()

for key in final_dict_tags:
  test_values.add(final_dict_tags[key])

print(test_values)

{'VERB', 'ADJ', 'NOUN', 'ADP', 'NUM', 'SYM', 'ART', 'PRON', 'PUNCT', 'AUX', 'ADV', 'CONJ', 'PROPN'}

### APLICANDO NO NOSSO DATASET DE REVIEWS DE HOTEL

In [412]:
path_reviews = "https://raw.githubusercontent.com/viniciusrpb/cic0269_natural_language_processing/main/datasets/corpora/training.csv"
dataset_reviews = pd.read_csv(path_reviews, sep=",", encoding="utf-8")
dataset_reviews

        Id                                               text  Expected
0        0  Ótima localização, bom atendimento, bom sinal ...         1
1        1  O hotel é bem localizado e silencioso, o que c...         1
2        2  O hotel é muito bom. O atendimento é excelente...         2
3        3  Hotel antigo, mal conservado e mal reformado, ...         0
4        4  Hotel bem localizado, perto de dois shopping, ...         2
...    ...                                                ...       ...
4995  4995  Hotel muito bem localizado, com shopping e dem...         2
4996  4996  Além de oferecer uma boa hospedagem com confor...         2
4997  4997  Hotel charmoso, bom atendimento, quartos confo...         2
4998  4998  O hotel fica super bem localizado, em frente a...         2
4999  4999  O serviço atendeu a todas as expectativas. Ide...         2

[5000 rows x 3 columns]

In [413]:
def normalize(sentence):
  new_sentence = re.sub(r"([\.|!|,|\'|\"|\(|\)|@|#|$|%|&|\*|\-|_|\+|=|\{|\}|\[|\]|~|^|:|]+)", r" \1 ", sentence)
  new_sentence = new_sentence.strip()
  new_sentence = new_sentence.lower()
  # print(new_sentence.lower())
  return new_sentence

In [414]:
dataset_reviews["normalized"] = dataset_reviews.text.apply(normalize)
dataset_reviews
dataset_reviews["splitted"] = dataset_reviews.normalized.apply(str.split)
dataset_reviews

,Id,text,Expected,normalized,splitted
0,0,"Ótima localização, bom atendimento, bom sinal ...",1,"ótima localização , bom atendimento , bom si...","[ótima, localização, ,, bom, atendimento, ,, b..."
1,1,"O hotel é bem localizado e silencioso, o que c...",1,"o hotel é bem localizado e silencioso , o que...","[o, hotel, é, bem, localizado, e, silencioso, ..."
2,2,O hotel é muito bom. O atendimento é excelente...,2,o hotel é muito bom . o atendimento é excelen...,"[o, hotel, é, muito, bom, ., o, atendimento, é..."
3,3,"Hotel antigo, mal conservado e mal reformado, ...",0,"hotel antigo , mal conservado e mal reformado...","[hotel, antigo, ,, mal, conservado, e, mal, re..."
4,4,"Hotel bem localizado, perto de dois shopping, ...",2,"hotel bem localizado , perto de dois shopping...","[hotel, bem, localizado, ,, perto, de, dois, s..."
...,...,...,...,...,...
4995,4995,"Hotel muito bem localizado, com shopping e dem...",2,"hotel muito bem localizado , com shopping e d...","[hotel, muito, bem, localizado, ,, com, shoppi..."
4996,4996,Além de oferecer uma boa hospedagem com confor...,2,além de oferecer uma boa hospedagem com confor...,"[além, de, oferecer, uma, boa, hospedagem, com..."
4997,4997,"Hotel charmoso, bom atendimento, quartos confo...",2,"hotel charmoso , bom atendimento , quartos c...","[hotel, charmoso, ,, bom, atendimento, ,, quar..."
4998,4998,"O hotel fica super bem localizado, em frente a...",2,"o hotel fica super bem localizado , em frente...","[o, hotel, fica, super, bem, localizado, ,, em..."
4999,4999,O serviço atendeu a todas as expectativas. Ide...,2,o serviço atendeu a todas as expectativas . i...,"[o, serviço, atendeu, a, todas, as, expectativ..."

In [415]:
def mapping(sentence):
  global final_dict_tags
  list_result = []
  for word in sentence:
    try:
      list_result.append(final_dict_tags[word])
    except Exception as e:
      list_result.append("X")
      # print(f"Word {word} Error:{e}")
  return list_result

In [416]:
dataset_reviews["gramatical"] = dataset_reviews.splitted.apply(mapping)
dataset_reviews

,Id,text,Expected,normalized,splitted,gramatical
0,0,"Ótima localização, bom atendimento, bom sinal ...",1,"ótima localização , bom atendimento , bom si...","[ótima, localização, ,, bom, atendimento, ,, b...","[X, X, PUNCT, ADJ, X, PUNCT, ADJ, X, ADP, X, P..."
1,1,"O hotel é bem localizado e silencioso, o que c...",1,"o hotel é bem localizado e silencioso , o que...","[o, hotel, é, bem, localizado, e, silencioso, ...","[ART, X, AUX, ADV, X, CONJ, ADJ, PUNCT, ART, C..."
2,2,O hotel é muito bom. O atendimento é excelente...,2,o hotel é muito bom . o atendimento é excelen...,"[o, hotel, é, muito, bom, ., o, atendimento, é...","[ART, X, AUX, ADV, ADJ, PUNCT, ART, X, AUX, AD..."
3,3,"Hotel antigo, mal conservado e mal reformado, ...",0,"hotel antigo , mal conservado e mal reformado...","[hotel, antigo, ,, mal, conservado, e, mal, re...","[X, ADJ, PUNCT, X, ADJ, CONJ, X, X, PUNCT, ADV..."
4,4,"Hotel bem localizado, perto de dois shopping, ...",2,"hotel bem localizado , perto de dois shopping...","[hotel, bem, localizado, ,, perto, de, dois, s...","[X, ADV, X, PUNCT, ADP, ADP, NUM, X, PUNCT, X,..."
...,...,...,...,...,...,...
4995,4995,"Hotel muito bem localizado, com shopping e dem...",2,"hotel muito bem localizado , com shopping e d...","[hotel, muito, bem, localizado, ,, com, shoppi...","[X, ADV, ADV, X, PUNCT, ADP, X, CONJ, ADV, X, ..."
4996,4996,Além de oferecer uma boa hospedagem com confor...,2,além de oferecer uma boa hospedagem com confor...,"[além, de, oferecer, uma, boa, hospedagem, com...","[ADP, ADP, VERB, ART, X, X, ADP, X, CONJ, X, X..."
4997,4997,"Hotel charmoso, bom atendimento, quartos confo...",2,"hotel charmoso , bom atendimento , quartos c...","[hotel, charmoso, ,, bom, atendimento, ,, quar...","[X, ADJ, PUNCT, ADJ, X, PUNCT, X, X, PUNCT, CO..."
4998,4998,"O hotel fica super bem localizado, em frente a...",2,"o hotel fica super bem localizado , em frente...","[o, hotel, fica, super, bem, localizado, ,, em...","[ART, X, VERB, X, ADV, X, PUNCT, ADP, X, ADP, ..."
4999,4999,O serviço atendeu a todas as expectativas. Ide...,2,o serviço atendeu a todas as expectativas . i...,"[o, serviço, atendeu, a, todas, as, expectativ...","[ART, X, X, ADP, PRON, ART, X, PUNCT, ADJ, ADP..."